// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "lvgl_games/yang/yang.h"

void ui_Game_screen_init(void)
{
    ui_Game = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Game, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GameBackToMain = lv_imgbtn_create(ui_Game);
    lv_imgbtn_set_src(ui_GameBackToMain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_123003138, NULL);
    lv_imgbtn_set_src(ui_GameBackToMain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_684857571, NULL);
    lv_obj_set_height(ui_GameBackToMain, 48);
    lv_obj_set_width(ui_GameBackToMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_GameBackToMain, 2);
    lv_obj_set_y(ui_GameBackToMain, 8);

    ui_Game2048Button = lv_btn_create(ui_Game);
    lv_obj_set_width(ui_Game2048Button, 100);
    lv_obj_set_height(ui_Game2048Button, 50);
    lv_obj_set_x(ui_Game2048Button, -75);
    lv_obj_set_y(ui_Game2048Button, -50);
    lv_obj_set_align(ui_Game2048Button, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Game2048Button, lv_color_hex(0xFF9F00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Game2048Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Game2048Label = lv_label_create(ui_Game2048Button);
    lv_obj_set_width(ui_Game2048Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Game2048Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Game2048Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Game2048Label, "2048");
    lv_obj_set_style_text_font(ui_Game2048Label, &ui_font_AlimamaShuHeiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameYangButton = lv_btn_create(ui_Game);
    lv_obj_set_width(ui_GameYangButton, 100);
    lv_obj_set_height(ui_GameYangButton, 50);
    lv_obj_set_x(ui_GameYangButton, 75);
    lv_obj_set_y(ui_GameYangButton, -50);
    lv_obj_set_align(ui_GameYangButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_GameYangButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GameYangButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameYangLabel = lv_label_create(ui_GameYangButton);
    lv_obj_set_width(ui_GameYangLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameYangLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GameYangLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GameYangLabel, "羊了个羊");
    lv_obj_set_style_text_font(ui_GameYangLabel, &ui_font_AlimamaShuHeiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameXiaoLeButton = lv_btn_create(ui_Game);
    lv_obj_set_width(ui_GameXiaoLeButton, 100);
    lv_obj_set_height(ui_GameXiaoLeButton, 50);
    lv_obj_set_x(ui_GameXiaoLeButton, -75);
    lv_obj_set_y(ui_GameXiaoLeButton, 50);
    lv_obj_set_align(ui_GameXiaoLeButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_GameXiaoLeButton, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GameXiaoLeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameXiaoLabel = lv_label_create(ui_GameXiaoLeButton);
    lv_obj_set_width(ui_GameXiaoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameXiaoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GameXiaoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GameXiaoLabel, "消消乐");
    lv_obj_set_style_text_font(ui_GameXiaoLabel, &ui_font_AlimamaShuHeiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GamePvzButton = lv_btn_create(ui_Game);
    lv_obj_set_width(ui_GamePvzButton, 100);
    lv_obj_set_height(ui_GamePvzButton, 50);
    lv_obj_set_x(ui_GamePvzButton, 75);
    lv_obj_set_y(ui_GamePvzButton, 50);
    lv_obj_set_align(ui_GamePvzButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_GamePvzButton, lv_color_hex(0xA84CF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GamePvzButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GamePvzLabel = lv_label_create(ui_GamePvzButton);
    lv_obj_set_width(ui_GamePvzLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GamePvzLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GamePvzLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GamePvzLabel, "植物大战僵尸");
    lv_obj_set_style_text_font(ui_GamePvzLabel, &ui_font_AlimamaShuHeiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GameBackToMain, ui_event_GameBackToMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Game2048Button, ui_event_Game2048Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GameYangButton, ui_event_GameYangButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GameXiaoLeButton, ui_event_GameXiaoLeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GamePvzButton, ui_event_GamePvzButton, LV_EVENT_ALL, NULL);

}

